import { Question } from "../../core/models/question.model";
import { TestRole } from "../../core/models/test.model";

export const BANK: Record<TestRole, Question[]> = {
    alumno: [
        // VISUAL (11)
        { id: 1,  text: 'Me gusta hojear libros y mirar ilustraciones.', type: 'visual' },
        { id: 2,  text: 'Me gusta ver las cosas ordenadas a mi alrededor.', type: 'visual' },
        { id: 3,  text: 'Encuentro cosas que otros pierden porque recuerdo dónde las vi.', type: 'visual' },
        { id: 4,  text: 'Me fijo en los detalles (ropa, errores de ortografía, cosas fuera de lugar).', type: 'visual' },
        { id: 5,  text: 'Encuentro rápido la página que busco y avanzo rápido en los cuadernos.', type: 'visual' },
        { id: 6,  text: 'Entiendo mejor cuando veo cómo se hace o me lo muestran.', type: 'visual' },
        { id: 7,  text: 'Me gusta armar rompecabezas.', type: 'visual' },
        { id: 8,  text: 'Se me da bien dibujar o hacer dibujos con buena forma.', type: 'visual' },
        { id: 9,  text: 'A veces me cuesta pronunciar bien algunas palabras.', type: 'visual' },
        { id: 10, text: 'Miro mucho la cara del profesor cuando explica.', type: 'visual' },
        { id: 11, text: 'Hablo poco en clase o respondo muy rápido.', type: 'visual' },

        // AUDITIVO (12)
        { id: 12, text: 'Casi nunca estoy callado; me gusta conversar.', type: 'auditivo' },
        { id: 13, text: 'Me gusta contar chistes y hacer reír.', type: 'auditivo' },
        { id: 14, text: 'Para escribir bien, digo en voz alta las palabras.', type: 'auditivo' },
        { id: 15, text: 'Si me dan un recado por teléfono, lo recuerdo.', type: 'auditivo' },
        { id: 16, text: 'Me gusta dirigir o ayudar a organizar a mi grupo.', type: 'auditivo' },
        { id: 17, text: 'Me gusta escuchar música.', type: 'auditivo' },
        { id: 18, text: 'A veces pongo excusas para las cosas.', type: 'auditivo' },
        { id: 19, text: 'Me aprendo fácil las letras de las canciones.', type: 'auditivo' },
        { id: 20, text: 'A veces soy un poco torpe para moverme.', type: 'auditivo' },
        { id: 21, text: 'Me cuesta calcular bien el tiempo o las distancias.', type: 'auditivo' },
        { id: 22, text: 'Cuento historias con facilidad.', type: 'auditivo' },
        { id: 23, text: 'Mi letra es regular y a veces invierto letras.', type: 'auditivo' },

        // KINESTÉSICO (13)
        { id: 24, text: 'Me gusta moverme mucho.', type: 'kinestesico' },
        { id: 25, text: 'Quiero tocar y sentir las cosas.', type: 'kinestesico' },
        { id: 26, text: 'Cuando camino en fila, paso la mano por la pared.', type: 'kinestesico' },
        { id: 27, text: 'A veces me apoyo en las puertas o toco las bancas al caminar.', type: 'kinestesico' },
        { id: 28, text: 'Cuando converso, toco el hombro o brazo de mis amigos.', type: 'kinestesico' },
        { id: 29, text: 'Hago muchos gestos cuando hablo.', type: 'kinestesico' },
        { id: 30, text: 'Prefiero escribir o tomar apuntes para recordar.', type: 'kinestesico' },
        { id: 31, text: 'Puedo desarmar un aparato y volver a armarlo.', type: 'kinestesico' },
        { id: 32, text: 'Siempre estoy jugando con algún objeto.', type: 'kinestesico' },
        { id: 33, text: 'Disfruto hacer cosas con las manos.', type: 'kinestesico' },
        { id: 34, text: 'Soy bueno en los deportes.', type: 'kinestesico' },
        { id: 35, text: 'A veces parezco distraído.', type: 'kinestesico' },
        { id: 36, text: 'Hago aviones de papel u otros objetos con papel.', type: 'kinestesico' },
    ],
    
    representante: [
        { id: 101,  text: 'Le gusta hojear libros y mirar ilustraciones; conserva un libro determinado.', type: 'visual' },
        { id: 102,  text: 'Le satisface mirar conjuntos de objetos y exige orden a su alrededor.', type: 'visual' },
        { id: 103,  text: 'Encuentra cosas que otros han perdido; recuerda dónde las vio.', type: 'visual' },
        { id: 104,  text: 'Observa detalles: cómo se viste alguien, errores de ortografía u objetos fuera de lugar.', type: 'visual' },
        { id: 105,  text: 'Encuentra una página fácilmente; completa la mitad de la página antes que los demás.', type: 'visual' },
        { id: 106,  text: 'No capta bien instrucciones orales; prefiere copiar o ver una demostración.', type: 'visual' },
        { id: 107,  text: 'Le gusta armar rompecabezas.', type: 'visual' },
        { id: 108,  text: 'Probablemente dibuja bien, al menos con buena proporción.', type: 'visual' },
        { id: 109,  text: 'Puede tener problemas de articulación al hablar.', type: 'visual' },
        { id: 1010, text: 'Observa de cerca la cara del profesor.', type: 'visual' },
        { id: 1011, text: 'Habla poco en clase; responde con pocas palabras o muy rápido.', type: 'visual' },

        { id: 2012, text: 'Nunca está callado; es conversador.', type: 'auditivo' },
        { id: 2013, text: 'Le encanta contar chistes; trata de ser gracioso.', type: 'auditivo' },
        { id: 2014, text: 'Es bueno en ortografía; dice en voz alta las palabras.', type: 'auditivo' },
        { id: 2015, text: 'Si recibe una llamada telefónica, recuerda el mensaje.', type: 'auditivo' },
        { id: 2016, text: 'Suele asumir el rol de líder.', type: 'auditivo' },
        { id: 2017, text: 'Le gusta escuchar música.', type: 'auditivo' },
        { id: 2018, text: 'Suele dar excusas para todo.', type: 'auditivo' },
        { id: 2019, text: 'Memoriza fácilmente letras de canciones.', type: 'auditivo' },
        { id: 2020, text: 'Puede ser torpe en su habilidad motriz.', type: 'auditivo' },
        { id: 2021, text: 'Puede tener una percepción pobre del tiempo y el espacio.', type: 'auditivo' },
        { id: 2022, text: 'Es bueno para contar cuentos.', type: 'auditivo' },
        { id: 2023, text: 'Su caligrafía es regular; puede invertir letras.', type: 'auditivo' },

        { id: 3024, text: 'Le gusta moverse.', type: 'kinestesico' },
        { id: 3025, text: 'Quiere tocar y sentirlo todo.', type: 'kinestesico' },
        { id: 3026, text: 'Suele pasar la mano por la pared al caminar en fila.', type: 'kinestesico' },
        { id: 3027, text: 'Se recuesta en marcos de puertas o toca las bancas al caminar.', type: 'kinestesico' },
        { id: 3028, text: 'Palmea en la espalda a sus amigos o toca el hombro durante una conversación.', type: 'kinestesico' },
        { id: 3029, text: 'Hace muchos gestos al hablar.', type: 'kinestesico' },
        { id: 3030, text: 'Con frecuencia escribe las cosas; necesita tomar apuntes.', type: 'kinestesico' },
        { id: 3031, text: 'Puede desarmar un aparato y volver a armarlo.', type: 'kinestesico' },
        { id: 3032, text: 'Juega continuamente con objetos.', type: 'kinestesico' },
        { id: 3033, text: 'Disfruta haciendo cosas con las manos.', type: 'kinestesico' },
        { id: 3034, text: 'Es bueno para los deportes.', type: 'kinestesico' },
        { id: 3035, text: 'Puede parecer distraído o que pierde el tiempo.', type: 'kinestesico' },
        { id: 3036, text: 'Suele hacer aviones de papel u objetos similares.', type: 'kinestesico' },
    ]
};